CREATE TABLE trabalhadores (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    nis VARCHAR(11),
    nome VARCHAR(255) NOT NULL,
    nome_social VARCHAR(255),
    data_nascimento DATE NOT NULL,
    sexo CHAR(1) NOT NULL,
    raca_cor CHAR(1),
    estado_civil CHAR(1),
    grau_instrucao VARCHAR(2),
    pais_nascimento VARCHAR(3) DEFAULT '105',
    pais_nacionalidade VARCHAR(3) DEFAULT '105',
    numero_ctps VARCHAR(11),
    serie_ctps VARCHAR(5),
    uf_ctps CHAR(2),
    data_emissao_ctps DATE,
    numero_rg VARCHAR(20),
    orgao_emissor_rg VARCHAR(10),
    uf_rg CHAR(2),
    data_emissao_rg DATE,
    numero_cnh VARCHAR(11),
    categoria_cnh VARCHAR(2),
    validade_cnh DATE,
    numero_rne VARCHAR(20),
    telefone VARCHAR(20),
    celular VARCHAR(20),
    email VARCHAR(255),
    cep VARCHAR(8),
    logradouro VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    banco VARCHAR(3),
    agencia VARCHAR(5),
    conta VARCHAR(20),
    tipo_conta CHAR(1),
    possui_deficiencia BOOLEAN DEFAULT FALSE,
    tipo_deficiencia VARCHAR(2),
    observacao_deficiencia TEXT,
    situacao VARCHAR(20) DEFAULT 'ATIVO',
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    foto_url VARCHAR(500),
    CONSTRAINT chk_cpf_valido CHECK (LENGTH(cpf) = 11)
);

CREATE TABLE vinculos (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    trabalhador_id UUID NOT NULL REFERENCES trabalhadores(id) ON DELETE CASCADE,
    empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    estabelecimento_id UUID REFERENCES estabelecimentos(id),
    matricula VARCHAR(30) NOT NULL,
    data_admissao DATE NOT NULL,
    tipo_admissao CHAR(1) NOT NULL,
    tipo_regime_trabalhista CHAR(1) NOT NULL,
    tipo_regime_previdenciario CHAR(1) NOT NULL,
    cadastro_inicial CHAR(1) DEFAULT 'S',
    categoria VARCHAR(3) NOT NULL,
    cargo_id UUID REFERENCES cargos(id),
    funcao_id UUID,
    lotacao_id UUID REFERENCES lotacoes(id),
    horario_id UUID REFERENCES horarios(id),
    tipo_jornada CHAR(1) NOT NULL,
    tipo_contrato CHAR(1) NOT NULL,
    data_inicio_contrato DATE NOT NULL,
    data_fim_contrato DATE,
    valor_salario DECIMAL(10,2) NOT NULL,
    unidade_salario CHAR(1) NOT NULL,
    tipo_salario CHAR(1) NOT NULL,
    data_desligamento DATE,
    motivo_desligamento VARCHAR(2),
    aviso_previo CHAR(1),
    data_aviso_previo DATE,
    ind_pagamento_aviso CHAR(1),
    protocolo_esocial VARCHAR(50),
    recibo_esocial VARCHAR(50),
    data_envio_esocial TIMESTAMP WITH TIME ZONE,
    status_esocial VARCHAR(20),
    situacao VARCHAR(20) DEFAULT 'ATIVO',
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(empresa_id, matricula)
);

CREATE TABLE dependentes (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    trabalhador_id UUID NOT NULL REFERENCES trabalhadores(id) ON DELETE CASCADE,
    cpf VARCHAR(11),
    nome VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    tipo_dependente VARCHAR(2) NOT NULL,
    sexo CHAR(1),
    dependente_irrf BOOLEAN DEFAULT FALSE,
    dependente_sf BOOLEAN DEFAULT FALSE,
    incapaz BOOLEAN DEFAULT FALSE,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_inativacao DATE
);
