CREATE TABLE afastamentos (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    vinculo_id UUID NOT NULL REFERENCES vinculos(id) ON DELETE CASCADE,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    motivo_afastamento VARCHAR(2) NOT NULL,
    descricao_motivo TEXT,
    codigo_cid VARCHAR(10),
    ind_acidente_trabalho BOOLEAN DEFAULT FALSE,
    ind_auxilio_doenca BOOLEAN DEFAULT FALSE,
    numero_beneficio VARCHAR(20),
    situacao VARCHAR(20) DEFAULT 'ATIVO',
    protocolo_esocial VARCHAR(50),
    recibo_esocial VARCHAR(50),
    data_envio_esocial TIMESTAMP WITH TIME ZONE,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE acidentes_trabalho (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    vinculo_id UUID NOT NULL REFERENCES vinculos(id) ON DELETE CASCADE,
    numero_cat VARCHAR(20) UNIQUE,
    data_acidente TIMESTAMP WITH TIME ZONE NOT NULL,
    hora_acidente TIME NOT NULL,
    tipo_acidente CHAR(1) NOT NULL,
    tipo_local_acidente CHAR(1) NOT NULL,
    descricao_local VARCHAR(255),
    logradouro VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    cep VARCHAR(8),
    pais VARCHAR(3) DEFAULT '105',
    parte_corpo_atingida VARCHAR(2),
    agente_causador VARCHAR(10),
    codigo_cid VARCHAR(10),
    situacao_geradora VARCHAR(9),
    descricao_acidente TEXT NOT NULL,
    houve_morte BOOLEAN DEFAULT FALSE,
    data_obito TIMESTAMP WITH TIME ZONE,
    houve_atendimento_medico BOOLEAN DEFAULT FALSE,
    duracao_tratamento INTEGER,
    houve_afastamento BOOLEAN DEFAULT FALSE,
    afastamento_id UUID REFERENCES afastamentos(id),
    testemunhas TEXT,
    cat_origem_id UUID REFERENCES acidentes_trabalho(id),
    protocolo_esocial VARCHAR(50),
    recibo_esocial VARCHAR(50),
    data_envio_esocial TIMESTAMP WITH TIME ZONE,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exames_medicos (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    vinculo_id UUID NOT NULL REFERENCES vinculos(id) ON DELETE CASCADE,
    tipo_exame CHAR(1) NOT NULL,
    data_exame DATE NOT NULL,
    nome_medico VARCHAR(255) NOT NULL,
    crm_medico VARCHAR(10) NOT NULL,
    uf_crm CHAR(2) NOT NULL,
    resultado CHAR(1) NOT NULL,
    observacoes TEXT,
    data_proximo_exame DATE,
    protocolo_esocial VARCHAR(50),
    recibo_esocial VARCHAR(50),
    data_envio_esocial TIMESTAMP WITH TIME ZONE,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
